- assets/css/style.css
- index.html
placed header in middle of the page.
> added header + position

- assets/css/style.css
- index.html
> made flashcards in a row

- assets/js/script.js
also added a console log to test functionality of given funcs in js project file
> amended time function to display decrementing time

- assets/css/style.css
- index.html
> add image link and style

- assets/css/style.css
- assets/js/script.js
Once the cards are matched, then they are removed from the board.
> flashcards flipped & matched & removed from the board

- index.html
Two images of a dog is on the card
> dog img's attached

- index.html
> elephant-img attached

- index.html
added the cat img to HTML twice
> cat's img updated

- assets/js/script.js
- index.html
hard coded flashcards in html and amended match function to recognize pairs
> match function fixed

- assets/js/script.js
Added new codes on line 133 on JS for the restart button.
> Debug restart issue

- assets/css/style.css
- assets/js/script.js
Added new codes to JS (remove cards to hide it) Need to work on the RESTART button
> updated the remove to hide

- assets/css/style.css
- assets/js/script.js
Function to display a message with a "Play Again" button" from line 137-157 on JS.
> added the play-again code

- assets/css/style.css
- assets/js/script.js
console.log added on JS lines 55-58 for record purposes
> Console.log update

- assets/css/style.css
- assets/js/script.js
Updated the CSS Style for play again feature
> Play again css

- assets/css/style.css
- assets/js/script.js
- index.html
Updated the HTML for the start button instead of restart
> Restart to start

- assets/css/style.css
- assets/js/script.js
- index.html
Updated the JS for the start & restart buttons.
> Restart to start js

- assets/css/style.css
- assets/js/script.js
- index.html
Local storage is updated and counts the seconds
> Local storage kol

- assets/css/style.css
- assets/js/script.js
- index.html
The game will ONLY start once you click the start button
> Game starts after clicking

- assets/css/style.css
- assets/js/script.js
- index.html
> Time taken

- index.html
Add the JS code from Bootstrap in the HTML at the end of the line.
> Bootstrap js

- index.html
Added a game difficulty button from the Bootstrap link
> Bootstrap dropdown

- assets/css/style.css
- index.html
Updated the buttons to a bigger size in the CSS
> Bs button update

- assets/css/style.css
- assets/js/script.js
- index.html
The difficulty buttons are functional now
> Buton function

- assets/css/style.css
- assets/js/script.js
- index.html
The difficulty buttons mirror the movement of the screen.
> Button movement

- assets/css/style.css
difficulty buttons now stay in absolute position on the game board
> amended z-index issue

- assets/js/script.js
should display an alert that instructs user on how to interact with the product upon page load
> Window alert

- assets/css/style.css
> Headerbackground

- assets/css/style.css
> Actionbuttoncolor

- assets/css/style.css
- assets/js/script.js
- index.html
reformatted footer to fit better on the page
> Footer edits

- assets/css/style.css
- assets/js/script.js
- index.html
css changes to message displayed upon end game state
> Winner msg edits

- assets/css/style.css
- assets/js/script.js
> Restart button

- assets/js/script.js
The restart button is functional
> Complete restart

- assets/css/style.css
working on responsive design, so far applied to bootstrap button div
> responsive design for smaller screens, bootstrap button application

- assets/css/style.css
dead space within app UI reformatted
> reformatted footer links css
